#!/bin/sh

# Detect which package manager command to use
if [ -f "pnpm-lock.yaml" ]; then
  package_manager_cmd="pnpx"
elif [ -f "yarn.lock" ]; then
  package_manager_cmd="yarn"
else
  package_manager_cmd="npx"
fi

# Run lint-staged
$package_manager_cmd lint-staged
